version: "3.9"

services:
  school_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./school:/usr/src/app/school

